---
title: 3ADV International Services
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: equalizer@3advservices.com
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lobortis
  suscipit imperdiet. Proin risus felis, porta vitae tempor id, malesuada ut ipsum.
  Sed laoreet semper sapien quis varius. Mauris eu turpis lorem. Praesent nec malesuada
  diam, eu suscipit est. Duis ut consequat mauris.
baseurl: ''
url: ''
twitter_username: liamjcooper
github_username: liamjcooper
address: Contact Address
phone: 555-555-5555
markdown: kramdown
sass:
  sass_dir: _sass/
  style: compressed
