---
title: 3ADV International Services Limited
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  testimonials:
    title: Testimonials
    output: false
  uploads:
    title: Uploads
    output: true
email: equalizer@3advservices.com
description: Welcome to 3ADV International Services. We are the partner of choice
  for your product sourcing requirements. We offer tailor-made solutions to help you
  source, manufacture, inspect, consolidate and ship your products, and our international
  network can offer assistance and advice at any stage of the supply chain.
baseurl: 
url: https://3advservices.com
address: Andrew James UK Ltd, Floor 3, 2 Lighthouse View, Spectrum Business Park,
  Seaham, SR7 7PR
phone: '0191 377 8358'
markdown: kramdown
img_dir: "/uploads/"
exclude:
- vendor
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-sitemap
- github-pages
whitelist:
- jekyll-redirect-from
sass:
  sass_dir: _sass
  style: compressed
