---
title: 3ADV International Services Limited
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  testimonials:
    title: Testimonials
    output: false
  uploads:
    title: Uploads
    output: true
email: equalizer@3advservices.com
description: We are 3ADV International Services Limited. We offer tailor-made solutions
  to help you source, manufacture, inspect, consolidate and ship your products.
baseurl:
url: https://3advservices.com
address: 7-8 Fox Cover Industrial Estate, Admiralty Way, Seaham, SR7 7DN, United Kingdom
markdown: kramdown
img_dir: "/uploads/"
exclude:
- vendor
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-sitemap
- github-pages
whitelist:
- jekyll-redirect-from
sass:
  sass_dir: _sass
  style: compressed
