---
title: 3ADV International Services
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  testimonials:
    title: Testimonials
    output: false
  uploads:
    title: Uploads
    output: true
email: equalizer@3advservices.com
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lobortis
  suscipit imperdiet. Proin risus felis, porta vitae tempor id, malesuada ut ipsum.
  Sed laoreet semper sapien quis varius. Mauris eu turpis lorem. Praesent nec malesuada
  diam, eu suscipit est. Duis ut consequat mauris.
baseurl: ''
url: https://3adv.siteleaf.net/
address: Andrew James UK Ltd, Floor 3, 2 Lighthouse View, Spectrum Business Park,
  Seaham, SR7 7PR
phone: '0191 377 8358'
markdown: kramdown
img_dir: "/uploads/"
exclude:
- vendor
plugins:
- jekyll-feed
- jekyll-redirect-from
- github-pages
whitelist:
- jekyll-redirect-from
sass:
  sass_dir: _sass
  style: compressed
---
