---
title: 3ADV International Services Limited
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  testimonials:
    title: Testimonials
    output: false
  uploads:
    title: Uploads
    output: true
email: contact@3advservices.com
description: We are 3ADV International Services Limited. We offer tailor-made solutions
  to help you source, manufacture, inspect, consolidate and ship your products.
baseurl: 
url: https://3advservices.com
address: Room 5-15, 13A/F South Tower, World Finance Centre, Harbour City, 17 Canton
  Road, Tsim Sha Tsui, Kowloon, Hong Kong
markdown: kramdown
img_dir: "/uploads/"
exclude:
- vendor
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-sitemap
- github-pages
whitelist:
- jekyll-redirect-from
sass:
  sass_dir: _sass
  style: compressed
